### ISSUE TITLE
Support using the SPI controller in a separate clock domain

### ISSUE THREAD

**Issue by piotr-binkowski** [litex-hub/litespi#23]
With that we could run the rest of the SoC at a slower frequency while running the SPI core at a higher frequency to get better SPI/XIP performance. I think that this could be achieved by simply adding AsyncFIFOs to streams between SPI cores and the PHY. 
What do you think? @enjoy-digital @mithro

**Comment by mithro** [comment]
A AsyncFIFO might cause a large latency hit?

I think you might be able to take advantage of the fact that clocks generated from the same source and phase aligned to reduce CDC delays.

I'm no CDC expert.

**Comment by kowalewskijan** [comment]
@enjoy-digital What do you think about this? Is there anything similar implemented in LiteX already?

**Comment by enjoy-digital** [comment]
@enjoy-digital: i would recommend using an AsyncFIFO for the CDC, this is the easiest solution and the more generic. If latency is too high and if we have more information about the clocks relationship, we could replace the AsyncFIFO with a module that will take advantage of this and would just optionally replace the AsyncFIFO, so the architecture will be the same.

You can find some similar code here:
- https://github.com/enjoy-digital/liteeth/blob/master/liteeth/mac/core.py#L103-L107
- https://github.com/enjoy-digital/usb3_pipe/blob/master/usb3_pipe/serdes.py#L259-L262
- https://github.com/enjoy-digital/usb3_pipe/blob/master/usb3_pipe/serdes.py#L305-L308

**Comment by kowalewskijan** [comment]
@enjoy-digital I understand that we can CDC streams and I think we should separate clkgen too, but how we can handle cross domain rw to CSRs? I mean e.g. these [registers](https://github.com/litex-hub/litespi/blob/master/litespi/__init__.py#L51-L52).

**Comment by enjoy-digital** [comment]
@kowalewskijan: sorry i saw your questions but haven't answered directly and then forgot... The  control signals you want to transfer to the PHY's clock domain are slow (configuration from the software) and not moving once configured, so that's probably better to just use MultiReg as done here for example: https://github.com/enjoy-digital/litejesd204b/blob/master/litejesd204b/core.py#L327-L369. If these CSRs are only affecting the PHY, you should also probably create them directly in the PHY.
