### ISSUE TITLE
Make 10000 cycle timeout configurable

### ISSUE THREAD

**Issue by tcal-x** [litex-hub/litespi#43]
https://github.com/litex-hub/litespi/blob/master/litespi/core/mmap.py#L106

When used in https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/digilent_arty.py, litespi has a 10000 cycle delay for each non-sequential load from flash.  If flash is read sequentially, I don't see the delay.

For some reason, I don't see this large delay on the (internal) HPS board, even for non-sequential loads.   I haven't had time to investigate why the behavior is different.   Instantiation: https://github.com/google/CFU-Playground/blob/main/soc/hps_soc.py#L143-L150 

@kgugala FYI

**Comment by kgugala** [comment]
> If flash is read sequentially, I don't see the delay.
This delay is used only if there is a necessity to drive CS (e.g. to send new read command when you change the read address). If you read the flash sequentially you can simply read next chunk of data without driving CS pin.

**Comment by zyp** [comment]
What is the rationale for the number 10000? For the flash chips I've looked at the minimum time to deassert CS is on the order of nanoseconds to tens of nanoseconds, i.e. on the order of one to ten cycles.

I suggest we add the minimum time as a property of the module so we can calculate the number of cycles required.

I'm also inclined to move enforcement of the minimum time to the PHY, so that it'll be enforced regardless of which module has control of CS. See #46 for related stuff I'm working on.
